# Generated by Django 3.2.6 on 2023-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_demandchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название графика')),
                ('image', models.ImageField(upload_to='charts/', verbose_name='График')),
            ],
            options={
                'verbose_name': 'График географии',
                'verbose_name_plural': 'Графики географии',
            },
        ),
    ]
