# Generated by Django 3.2.6 on 2023-01-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_geochart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('skills', models.TextField(verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Ключевой навыки',
                'verbose_name_plural': 'Ключевый навыки',
            },
        ),
    ]
